### ISSUE TITLE
Minimum RAM requirements

### ISSUE THREAD

**Issue by quazgar** [OBrink/DECIMER.ai#64]
Hi,

I just tried to run the Docker image following the instructions. This froze my machine, because all my memory (16GB + swap) was eaten.  Could you maybe put some minimum system requirements into the README.md?

**Comment by OBrink** [comment]
Hey @quazgar

Thanks for your message. 

I just tested the default configuration, and according to Docker, it needs approximately 19 GB of RAM to run it. This is specified on the [Wiki page](https://github.com/OBrink/DECIMER.ai/wiki) where you can also find instructions on how to run the app with lower hardware requirements (9 GB of RAM).

The link to the Wiki along with the following remark is already in the README, so I don't see the need to add more:
`Instructions on how to set up a smaller version of DECIMER.ai - Currently, the default version in this repository consumes approximately 20 GB of memory. This can be scaled down drastically (at the cost of parallel processing speed).`

I hope this helps :)

Otto

**Comment by OBrink** [comment]
Great. Please let us know if you run into further problems! :)
