### ISSUE TITLE
Server error : 500

### ISSUE THREAD

**Issue by Kohulan** [OBrink/DECIMER.ai#66]
Image causing the issue:
![PXL_20230628_132147022~2](https://github.com/OBrink/DECIMER.ai/assets/30716951/74e78bc6-3d60-4e19-9c35-e712255108f7)

**Comment by OBrink** [comment]
I have to make sure that I have not broken something, and I need to restart the Docker image hosted on https://decimer.ai. I will take care of this first thing tomorrow morning
