### ISSUE TITLE
Stereo enabled protons are often detected as CH3 groups

### ISSUE THREAD

**Issue by steinbeck** [OBrink/DECIMER.ai#69]
Stereo enabled protons are often detected as CH3 groups (see screenshot). Maybe, adding more examples in the training data will alleviate this problem. 
![stereoprotonbug](https://github.com/OBrink/DECIMER.ai/assets/107318/d88757d4-8ed8-47ca-9f12-f0ff3bf7a89b)

**Comment by OBrink** [comment]
This should hopefully be fixed in the next version trained on RanDepict 1.1.8. Currently, the model often interprets hydrogen atoms wrongly.

**Comment by Kohulan** [comment]
It is now fixed:
<img width="772" alt="image" src="https://github.com/user-attachments/assets/3af03faa-57d2-4c35-8db3-2019cf3cb27a">
