### ISSUE TITLE
Feature request pasting images from the clipboard

### ISSUE THREAD

**Issue by ChrisLinnNuvisan** [OBrink/DECIMER.ai#71]
Hi,

I have a feature request. It would be nice to upload images which are in your clipboard. This is a feature request of actual users. For example they use the Windows snipping tool to grab a view with one or more structures from any application. Currently they need to save the snipped images to a file and upload it. The image is already in the clipboard when using the Snipping tool, therefore a simple paste on the page would avoid saving it to a file and uploading it.

Any Javascript experts around here to add this?

Best regards,
Chris

**Comment by Kohulan** [comment]
Hi @ChrisLinnNuvisan ,

It is definitely a nice idea to implement, If you did accomplish this by yourself please send a pull request. We would be happy to add this.

Kind regards,
Kohulan

**Comment by OBrink** [comment]
I have looked into an area for just dragging images from another website before. The main problem I ran into was that I did not manage to have the upload button have these two functionalities at the same time. On the other hand, I did not spent a huge amount of time on it when I did not find a solution immediately. I would highly appreciate every type of help here!

**Comment by Kohulan** [comment]
Pasting from the clipboard is now available:
https://github.com/Steinbeck-Lab/DECIMER.ai/pull/1
