### ISSUE TITLE
Will internal data be sent out when running DECIMER.ai locally

### ISSUE THREAD

**Issue by zhentg** [OBrink/DECIMER.ai#72]
Dear developers,

I tested https://decimer.ai/ and found it awesome.
I want to deploy internally for data privacy. I wonder if internal data will be sent out when running DECIMER.ai locally?

Best
Zhenting

**Comment by OBrink** [comment]
Dear @zhentg,

There is a Google Analytics tag and a Matomo tag in the code, but all they do is track user numbers. If you would like to remove them, go to [DECIMER.ai](https://github.com/OBrink/DECIMER.ai/tree/main)/[resources](https://github.com/OBrink/DECIMER.ai/tree/main/resources)/[views](https://github.com/OBrink/DECIMER.ai/tree/main/resources/views)/[layouts](https://github.com/OBrink/DECIMER.ai/tree/main/resources/views/layouts)
/default.blade.php and delete lines 17-38:
```
<!--Global site tag (gtag.js) - Google Analytics-->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-VKSWMKC79R"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-VKSWMKC79R');
	</script>
	<script>
		var _paq = window._paq = window._paq || [];
		/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
		_paq.push(['trackPageView']);
		_paq.push(['enableLinkTracking']);
		(function() {
			var u="//matomo.nfdi4chem.de/";
			_paq.push(['setTrackerUrl', u+'matomo.php']);
			_paq.push(['setSiteId', '2']);
			var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
			g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
		})();
	</script>
```

Apart from the tags for counting user numbers, we do not track or save any of your data. Even the problem report button only copies the reported images into a different local directory. When you run the DECIMER.ai app locally, it does require internet access, everything runs on your machine.

**Comment by steinbeck** [comment]
I assume the last sentence should be "does *not* require internet access".

**Comment by zhentg** [comment]
Thanks for the clarification. In this context, I will try to setup a local DECIMER.ai service.
