### ISSUE TITLE
Error running local installation

### ISSUE THREAD

**Issue by zhentg** [OBrink/DECIMER.ai#73]
Dear developers,

I installed DECIMER on my local Linux box.
After I upload an image file, the following error pops up. Could you help to figure out the reason?

ErrorException
count(): Parameter must be an array or an object that implements Countable
http://192.168.1.22/decimer-segmentation

Best

**Comment by OBrink** [comment]
Dear @zhentg,

Thank you for your feedback. The error simply means that the app does not get a result from the segmentation model.

Two suggestions:

1) Sometimes the models need a while to load. After starting the app with docker-compose, wait 5 minutes, then try again,
2) What hardware are you running it on? If you just pull the repository and run it, the app requires approximately 20 GB of RAM. You can find a tutorial on how to bring that down to 9 GB of RAM here - https://github.com/OBrink/DECIMER.ai/wiki.

Let me know if this helps! If it does not, I am more than happy to provide further assistance!

Kind regards,
Otto

**Comment by yipy0005** [comment]
Hi, I tried the tutorial at https://github.com/OBrink/DECIMER.ai/wiki, waited for 5 mins and the same error popped up when I uploaded an image or a PDF of a molecule.

Appreciate any help on this. :)

**Comment by OBrink** [comment]
@yipy0005 @zhentg

I have cloned a fresh version of the repository and have set it up according to the instructions in the README, and I cannot replicate the problem. As it's Docker, there should not be any system-dependent issues, unless your hardware is not enough to run the app.

The error tells us that the app sends a request to a preloaded instance of the segmentation model but does not get a response. This should not happen unless the model has not been loaded properly. 

After modifying the supervisor configuration, have you modified the `num_ports` variable in `decimer_segmentation_client.py`, `decimer_predictor_client.py`, `stout_predictor_client.py` and `decimer_classifier_client.py` accordingly?

1) Could you post the output that you get when running `docker stats` when the app is running?
2) Could you post the content of `storage/logs/segmentation_socket_server_23456.log`?

**Comment by zhentg** [comment]
> Dear @zhentg,
> 
> Thank you for your feedback. The error simply means that the app does not get a result from the segmentation model.
> 
> Two suggestions:
> 
> 1. Sometimes the models need a while to load. After starting the app with docker-compose, wait 5 minutes, then try again,
> 2. What hardware are you running it on? If you just pull the repository and run it, the app requires approximately 20 GB of RAM. You can find a tutorial on how to bring that down to 9 GB of RAM here - https://github.com/OBrink/DECIMER.ai/wiki.
> 
> Let me know if this helps! If it does not, I am more than happy to provide further assistance!
> 
> Kind regards, Otto

Dear Otto,

Thanks for the help.
I tested my local DECIMER today, and it really works.
So it seems I need to wait for 5 min for the model loading. Would you mind to added this notion to the installation note?

Best regards
Zhenting

**Comment by OBrink** [comment]
Dear Zhenting,

I'm happy to hear that it is working now. I have added a remark in the README. I'll have a look at showing if the models have been loaded and catching that error properly instead of just crashing when that happens. #57

Best regards
Otto
