### ISSUE TITLE
How to run the image directly

### ISSUE THREAD

**Issue by dreamfly999** [OBrink/DECIMER.ai#78]
Thank you for developing such a successful web page and I successfully localized DECIMER.ai, but because the machine restarted unexpectedly, how to directly start the image, I used the following command line, but it did not work:
`docker run -d --name decimerai-supervisor-2 app`
`docker run -d --name decimerai-app-2 app`
`docker run -d --name decimerai-nginx-4  nginx:alpine`

The program running in the background of docker is shown as follows:
![image](https://github.com/OBrink/DECIMER.ai/assets/34122505/f360ed79-74bf-43bd-842e-e13a53e2bebb)

**Comment by OBrink** [comment]
Hey @dreamfly999,

After having built the app using `docker-compose up --build -d` once, you can just run the same command without the `--build` flag: `docker-compose up -d`.

Kind regards,
Otto

**Comment by dreamfly999** [comment]
Ok, thank you very much
